"""General freight characteristics for each US state (50 states, no DC).

Used to build state dispatch pages. Entries describe broad, well-known
geography and freight patterns only; review for accuracy whenever edited.
Neighbor lists exclude point-only (Four Corners) contacts.
"""

STATES = {
    "AL": {
        "hubs": ["Birmingham", "Mobile", "Montgomery", "Huntsville"],
        "interstates": ["I-65", "I-20", "I-59", "I-10", "I-85", "I-22"],
        "freight": ["auto parts and vehicles", "steel and metals", "lumber and wood products", "poultry", "chemicals"],
        "ports": ["Port of Mobile"],
        "neighbors": ["FL", "GA", "TN", "MS"],
        "equipment": ["Flatbed", "Dry Van", "Reefer"],
        "note": "Alabama combines a growing auto manufacturing base with steel, timber and poultry, and the Port of Mobile links Gulf shipping to inland plants.",
    },
    "AK": {
        "hubs": ["Anchorage", "Fairbanks", "Seward"],
        "interstates": ["Glenn Highway", "Parks Highway", "Seward Highway", "Alaska Highway"],
        "freight": ["groceries and consumer goods", "oil field equipment", "seafood", "construction materials"],
        "ports": ["Port of Alaska (Anchorage)", "Port of Seward"],
        "neighbors": [],
        "equipment": ["Flatbed", "Dry Van", "Reefer"],
        "note": "Alaska relies on a small highway network fed mainly by ocean freight into Anchorage, with long hauls north to Fairbanks and oil field supply runs. Weather and distance shape every load.",
    },
    "AZ": {
        "hubs": ["Phoenix", "Tucson", "Flagstaff", "Yuma"],
        "interstates": ["I-10", "I-17", "I-40", "I-8", "I-19"],
        "freight": ["fresh produce", "electronics and semiconductors", "building materials", "retail goods", "copper"],
        "ports": ["Nogales border crossing", "San Luis border crossing"],
        "neighbors": ["CA", "NV", "UT", "NM"],
        "equipment": ["Reefer", "Dry Van", "Flatbed"],
        "note": "Arizona is a key gateway for Mexican produce through Nogales, and the Phoenix area serves as a distribution hub for the Southwest. Winter vegetables from the Yuma area add strong seasonal reefer demand.",
    },
    "AR": {
        "hubs": ["Little Rock", "Fort Smith", "Springdale", "West Memphis"],
        "interstates": ["I-40", "I-30", "I-55", "I-49"],
        "freight": ["poultry", "rice", "retail goods", "timber and paper", "steel"],
        "ports": ["Port of Little Rock"],
        "neighbors": ["MO", "TN", "MS", "LA", "TX", "OK"],
        "equipment": ["Reefer", "Dry Van", "Flatbed"],
        "note": "Arkansas is home to major retail and trucking headquarters in the northwest and large poultry processing operations, while I-40 carries heavy cross-country traffic between Memphis and Oklahoma.",
    },
    "CA": {
        "hubs": ["Los Angeles", "Ontario", "Oakland", "Fresno", "Sacramento"],
        "interstates": ["I-5", "I-10", "I-15", "I-80", "I-40", "I-8"],
        "freight": ["imported containers", "fresh produce", "wine and beverages", "electronics", "dairy"],
        "ports": ["Port of Los Angeles", "Port of Long Beach", "Port of Oakland", "Otay Mesa border crossing"],
        "neighbors": ["OR", "NV", "AZ"],
        "equipment": ["Reefer", "Dry Van", "Power Only"],
        "note": "California's Los Angeles and Long Beach ports feed warehouses in the Inland Empire, while the Central Valley ships produce nationwide year-round. State emissions rules affect which trucks can operate.",
    },
    "CO": {
        "hubs": ["Denver", "Colorado Springs", "Greeley", "Pueblo", "Grand Junction"],
        "interstates": ["I-25", "I-70", "I-76"],
        "freight": ["beef and meat products", "beverages", "oil and gas equipment", "building materials", "retail goods"],
        "ports": [],
        "neighbors": ["WY", "NE", "KS", "OK", "NM", "UT"],
        "equipment": ["Reefer", "Dry Van", "Flatbed"],
        "note": "Denver is the main distribution center for the Rocky Mountain region, while northern Colorado contributes meatpacking and energy freight. Mountain passes on I-70 bring winter chain laws and closures.",
    },
    "CT": {
        "hubs": ["Hartford", "New Haven", "Bridgeport", "Waterbury"],
        "interstates": ["I-95", "I-84", "I-91", "I-395"],
        "freight": ["aerospace components", "machinery", "consumer goods", "pharmaceuticals"],
        "ports": ["Port of New Haven"],
        "neighbors": ["NY", "MA", "RI"],
        "equipment": ["Dry Van", "Box Truck", "Flatbed"],
        "note": "Connecticut sits on the busy I-95 corridor between New York and Boston, with precision manufacturing and aerospace supply chains generating short-haul and regional freight.",
    },
    "DE": {
        "hubs": ["Wilmington", "Dover", "Newark", "Seaford"],
        "interstates": ["I-95", "I-495", "I-295"],
        "freight": ["fresh fruit imports", "poultry", "chemicals", "consumer goods"],
        "ports": ["Port of Wilmington"],
        "neighbors": ["MD", "PA", "NJ"],
        "equipment": ["Reefer", "Dry Van"],
        "note": "Delaware's Port of Wilmington handles large volumes of imported fruit and other perishables, and the Delmarva Peninsula is a major poultry region. I-95 links the state to Philadelphia and Baltimore.",
    },
    "FL": {
        "hubs": ["Miami", "Jacksonville", "Orlando", "Tampa", "Lakeland"],
        "interstates": ["I-95", "I-75", "I-10", "I-4"],
        "freight": ["citrus and fresh produce", "imported goods", "building materials", "consumer goods", "flowers"],
        "ports": ["PortMiami", "Port Everglades", "JAXPORT", "Port Tampa Bay"],
        "neighbors": ["GA", "AL"],
        "equipment": ["Reefer", "Dry Van", "Flatbed"],
        "note": "Florida is a heavy consumer state, so far more freight arrives than leaves, which pressures outbound rates. Seasonal produce and multiple seaports keep reefer and dry van demand strong in Central Florida.",
    },
    "GA": {
        "hubs": ["Atlanta", "Savannah", "Macon", "Augusta", "Dalton"],
        "interstates": ["I-75", "I-85", "I-95", "I-20", "I-16", "I-285"],
        "freight": ["imported containers", "poultry", "carpet and flooring", "paper and pulp", "peanuts"],
        "ports": ["Port of Savannah", "Port of Brunswick"],
        "neighbors": ["FL", "AL", "TN", "NC", "SC"],
        "equipment": ["Dry Van", "Reefer", "Power Only"],
        "note": "Georgia pairs the Port of Savannah with Atlanta's large distribution network, making it a Southeast freight crossroads. Dalton's flooring industry and statewide poultry production add steady outbound freight.",
    },
    "HI": {
        "hubs": ["Honolulu", "Kapolei", "Hilo", "Kahului"],
        "interstates": ["H-1", "H-2", "H-3"],
        "freight": ["groceries and consumer goods", "construction materials", "fresh produce", "fuel"],
        "ports": ["Honolulu Harbor", "Kahului Harbor", "Hilo Harbor"],
        "neighbors": [],
        "equipment": ["Box Truck", "Dry Van", "Reefer"],
        "note": "Hawaii depends almost entirely on ocean shipping, so trucking is short-haul drayage and local delivery from harbors on each island. Most activity centers on Honolulu Harbor and Oahu.",
    },
    "ID": {
        "hubs": ["Boise", "Idaho Falls", "Pocatello", "Twin Falls", "Nampa"],
        "interstates": ["I-84", "I-15", "I-90", "I-86"],
        "freight": ["potatoes", "dairy and cheese", "lumber", "sugar beets", "frozen foods"],
        "ports": [],
        "neighbors": ["WA", "OR", "NV", "UT", "WY", "MT"],
        "equipment": ["Reefer", "Flatbed", "Dry Van"],
        "note": "Idaho is best known for potatoes and frozen potato products, and the Magic Valley is a major dairy region. Northern Idaho adds timber and lumber freight along I-90.",
    },
    "IL": {
        "hubs": ["Chicago", "Joliet", "Peoria", "Rockford", "Springfield"],
        "interstates": ["I-55", "I-57", "I-80", "I-90", "I-94", "I-74"],
        "freight": ["intermodal containers", "corn and soybeans", "machinery", "food products", "consumer goods"],
        "ports": ["Joliet and Elwood intermodal terminals", "Chicago rail yards", "Port of Chicago"],
        "neighbors": ["WI", "IA", "MO", "KY", "IN"],
        "equipment": ["Dry Van", "Power Only", "Flatbed"],
        "note": "Chicago is the nation's leading rail interchange, so Illinois trucking revolves around intermodal drayage and the warehouse clusters near Joliet. Downstate Illinois moves large volumes of grain.",
    },
    "IN": {
        "hubs": ["Indianapolis", "Fort Wayne", "Gary", "Evansville", "Elkhart"],
        "interstates": ["I-65", "I-70", "I-69", "I-74", "I-94", "I-90"],
        "freight": ["auto parts and vehicles", "steel", "recreational vehicles", "pharmaceuticals", "corn and soybeans"],
        "ports": ["Port of Indiana-Burns Harbor"],
        "neighbors": ["IL", "MI", "OH", "KY"],
        "equipment": ["Dry Van", "Flatbed", "Step Deck"],
        "note": "Indiana calls itself the Crossroads of America, with Indianapolis serving as a major distribution hub. Steel mills in the northwest and RV manufacturing around Elkhart generate heavy flatbed freight.",
    },
    "IA": {
        "hubs": ["Des Moines", "Cedar Rapids", "Davenport", "Sioux City", "Council Bluffs"],
        "interstates": ["I-80", "I-35", "I-29", "I-380", "I-74"],
        "freight": ["corn and soybeans", "pork", "ethanol", "farm machinery", "eggs"],
        "ports": [],
        "neighbors": ["MN", "WI", "IL", "MO", "NE", "SD"],
        "equipment": ["Reefer", "Dry Van", "Flatbed"],
        "note": "Iowa's freight is driven by agriculture, including grain, pork processing and ethanol, along with farm equipment manufacturing. I-80 carries heavy coast-to-coast traffic across the state.",
    },
    "KS": {
        "hubs": ["Kansas City", "Wichita", "Topeka", "Salina", "Garden City"],
        "interstates": ["I-70", "I-35", "I-135"],
        "freight": ["wheat and grain", "beef", "aircraft parts", "farm machinery"],
        "ports": ["Logistics Park Kansas City"],
        "neighbors": ["NE", "MO", "OK", "CO"],
        "equipment": ["Reefer", "Flatbed", "Dry Van"],
        "note": "Kansas combines wheat and large beef packing plants in the southwest with aircraft manufacturing in Wichita. The Kansas City side hosts large intermodal and warehouse facilities.",
    },
    "KY": {
        "hubs": ["Louisville", "Lexington", "Bowling Green", "Covington", "Paducah"],
        "interstates": ["I-65", "I-64", "I-75", "I-71", "I-24", "I-69"],
        "freight": ["auto parts and vehicles", "bourbon and spirits", "air cargo", "coal", "appliances"],
        "ports": ["Louisville air cargo hub", "Northern Kentucky air cargo hub"],
        "neighbors": ["IL", "IN", "OH", "WV", "VA", "TN", "MO"],
        "equipment": ["Dry Van", "Flatbed", "Power Only"],
        "note": "Kentucky hosts major air cargo hubs in Louisville and Northern Kentucky, plus large auto assembly plants. Its central location puts much of the eastern US population within a day's drive.",
    },
    "LA": {
        "hubs": ["New Orleans", "Baton Rouge", "Shreveport", "Lafayette", "Lake Charles"],
        "interstates": ["I-10", "I-20", "I-49", "I-55", "I-12"],
        "freight": ["petrochemicals", "oil and gas equipment", "grain exports", "seafood", "sugar"],
        "ports": ["Port of New Orleans", "Port of South Louisiana", "Port of Lake Charles"],
        "neighbors": ["TX", "AR", "MS"],
        "equipment": ["Flatbed", "Dry Van", "Step Deck"],
        "note": "Louisiana's Mississippi River ports and Gulf Coast refineries make petrochemicals and energy equipment central to its trucking market. The I-10 corridor links Houston, Baton Rouge and New Orleans.",
    },
    "ME": {
        "hubs": ["Portland", "Bangor", "Lewiston", "Augusta"],
        "interstates": ["I-95", "I-295", "I-395"],
        "freight": ["lumber and wood products", "paper", "seafood", "potatoes", "blueberries"],
        "ports": ["Port of Portland (Maine)", "Houlton border crossing"],
        "neighbors": ["NH"],
        "equipment": ["Flatbed", "Reefer", "Dry Van"],
        "note": "Maine's freight centers on forest products, seafood and Aroostook County potatoes. As an end-of-the-line state, inbound loads usually outnumber outbound, and northern lanes see harsh winters.",
    },
    "MD": {
        "hubs": ["Baltimore", "Hagerstown", "Frederick", "Salisbury"],
        "interstates": ["I-95", "I-70", "I-83", "I-81", "I-68", "I-695"],
        "freight": ["imported vehicles", "consumer goods", "poultry", "seafood", "pharmaceuticals"],
        "ports": ["Port of Baltimore"],
        "neighbors": ["VA", "WV", "PA", "DE"],
        "equipment": ["Dry Van", "Reefer", "Power Only"],
        "note": "The Port of Baltimore is a leading East Coast port for roll-on roll-off vehicles, and Hagerstown sits where I-70 and I-81 cross. The Eastern Shore adds poultry and seafood freight.",
    },
    "MA": {
        "hubs": ["Boston", "Worcester", "Springfield", "New Bedford"],
        "interstates": ["I-90", "I-95", "I-93", "I-91", "I-495", "I-84"],
        "freight": ["medical devices", "seafood", "consumer goods", "electronics"],
        "ports": ["Port of Boston", "Port of New Bedford"],
        "neighbors": ["RI", "CT", "NY", "VT", "NH"],
        "equipment": ["Dry Van", "Box Truck", "Reefer"],
        "note": "Massachusetts is a dense consumer market where inbound freight dominates and urban delivery in Boston is tight. New Bedford is a major fishing port, and the I-495 belt hosts many distribution centers.",
    },
    "MI": {
        "hubs": ["Detroit", "Grand Rapids", "Lansing", "Flint", "Saginaw"],
        "interstates": ["I-75", "I-94", "I-96", "I-69", "I-196"],
        "freight": ["auto parts and vehicles", "steel", "furniture", "fruit", "machinery"],
        "ports": ["Ambassador Bridge", "Blue Water Bridge (Port Huron)", "Detroit-Windsor Tunnel"],
        "neighbors": ["OH", "IN", "WI"],
        "equipment": ["Dry Van", "Flatbed", "Power Only"],
        "note": "Michigan is the center of the US auto industry, and Detroit's bridge to Windsor is one of the busiest US-Canada crossings. Just-in-time auto parts shipments make timing critical.",
    },
    "MN": {
        "hubs": ["Minneapolis", "St. Paul", "Duluth", "Rochester", "St. Cloud"],
        "interstates": ["I-35", "I-94", "I-90", "I-35W", "I-35E"],
        "freight": ["grain", "food products", "iron ore", "medical devices", "turkey"],
        "ports": ["Port of Duluth-Superior"],
        "neighbors": ["WI", "IA", "SD", "ND"],
        "equipment": ["Dry Van", "Reefer", "Flatbed"],
        "note": "The Twin Cities anchor Minnesota's food processing and distribution economy, while the Iron Range and Duluth's Great Lakes port move ore and grain. Winter weather heavily affects northern lanes.",
    },
    "MS": {
        "hubs": ["Jackson", "Gulfport", "Tupelo", "Meridian", "Hattiesburg"],
        "interstates": ["I-55", "I-20", "I-10", "I-59", "I-22"],
        "freight": ["poultry", "lumber and timber", "furniture", "auto parts and vehicles", "catfish"],
        "ports": ["Port of Gulfport", "Port of Pascagoula"],
        "neighbors": ["LA", "AR", "TN", "AL"],
        "equipment": ["Flatbed", "Reefer", "Dry Van"],
        "note": "Mississippi's freight leans on poultry, timber and the Tupelo furniture industry, plus auto assembly plants. Gulf Coast ports at Gulfport and Pascagoula connect to shipbuilding and imports.",
    },
    "MO": {
        "hubs": ["Kansas City", "St. Louis", "Springfield", "Joplin", "Columbia"],
        "interstates": ["I-70", "I-44", "I-55", "I-35", "I-29"],
        "freight": ["auto parts and vehicles", "grain", "beef and pork", "chemicals", "consumer goods"],
        "ports": ["Kansas City rail yards", "St. Louis rail and barge terminals"],
        "neighbors": ["IA", "IL", "KY", "TN", "AR", "OK", "KS", "NE"],
        "equipment": ["Dry Van", "Reefer", "Flatbed"],
        "note": "Missouri's two major metros, Kansas City and St. Louis, are rail and river crossroads linked by I-70. Its central location makes it a staging point for freight heading in every direction.",
    },
    "MT": {
        "hubs": ["Billings", "Missoula", "Great Falls", "Bozeman", "Butte"],
        "interstates": ["I-90", "I-15", "I-94"],
        "freight": ["wheat and grain", "cattle", "lumber", "oil and gas equipment", "minerals"],
        "ports": ["Sweetgrass border crossing"],
        "neighbors": ["ID", "WY", "SD", "ND"],
        "equipment": ["Flatbed", "Step Deck", "Hotshot"],
        "note": "Montana is a long-distance, low-density market where wheat, cattle, lumber and energy dominate. Freight volumes are thin, so outbound loads are harder to find than inbound.",
    },
    "NE": {
        "hubs": ["Omaha", "Lincoln", "Grand Island", "North Platte"],
        "interstates": ["I-80", "I-76", "I-680"],
        "freight": ["beef", "corn and soybeans", "ethanol", "farm machinery"],
        "ports": ["North Platte rail yard"],
        "neighbors": ["SD", "IA", "MO", "KS", "CO", "WY"],
        "equipment": ["Reefer", "Dry Van", "Flatbed"],
        "note": "Nebraska is a major beef packing state, and I-80 runs the length of the state carrying transcontinental freight. Corn, ethanol and agricultural equipment round out its freight base.",
    },
    "NV": {
        "hubs": ["Reno", "Las Vegas", "Sparks", "Elko"],
        "interstates": ["I-15", "I-80", "I-11", "I-580"],
        "freight": ["retail and e-commerce goods", "hospitality supplies", "mining equipment", "batteries and electronics"],
        "ports": [],
        "neighbors": ["CA", "OR", "ID", "UT", "AZ"],
        "equipment": ["Dry Van", "Reefer", "Flatbed"],
        "note": "Northern Nevada around Reno hosts large distribution and battery manufacturing sites serving California, while Las Vegas is a heavy inbound market for food and hospitality goods. Mining drives rural freight.",
    },
    "NH": {
        "hubs": ["Manchester", "Nashua", "Concord", "Portsmouth"],
        "interstates": ["I-93", "I-89", "I-95"],
        "freight": ["consumer goods", "electronics", "lumber", "machinery"],
        "ports": ["Port of Portsmouth"],
        "neighbors": ["ME", "MA", "VT"],
        "equipment": ["Dry Van", "Box Truck", "Flatbed"],
        "note": "New Hampshire's freight market is concentrated in the southern tier near Boston, with retail distribution and light manufacturing. Many loads move through the state on I-95 toward Maine.",
    },
    "NJ": {
        "hubs": ["Newark", "Elizabeth", "Edison", "Secaucus", "Camden"],
        "interstates": ["I-95", "I-78", "I-80", "I-287", "I-295"],
        "freight": ["imported containers", "pharmaceuticals", "consumer goods", "chemicals", "food products"],
        "ports": ["Port Newark-Elizabeth", "Port of New York and New Jersey"],
        "neighbors": ["NY", "PA", "DE"],
        "equipment": ["Dry Van", "Power Only", "Reefer"],
        "note": "New Jersey handles most of the container traffic for the Port of New York and New Jersey, and the Turnpike corridor is lined with warehouses. Drayage and short-haul distribution dominate.",
    },
    "NM": {
        "hubs": ["Albuquerque", "Las Cruces", "Santa Fe", "Farmington"],
        "interstates": ["I-25", "I-40", "I-10"],
        "freight": ["oil and gas equipment", "chile peppers and produce", "dairy", "pecans"],
        "ports": ["Santa Teresa border crossing"],
        "neighbors": ["AZ", "CO", "OK", "TX"],
        "equipment": ["Flatbed", "Reefer", "Hotshot"],
        "note": "New Mexico sees heavy through traffic on I-40 and I-10, while the Permian Basin in the southeast generates oil field freight. The Santa Teresa crossing is growing as a Mexico trade gateway.",
    },
    "NY": {
        "hubs": ["New York City", "Buffalo", "Albany", "Syracuse", "Rochester"],
        "interstates": ["I-87", "I-90", "I-81", "I-84", "I-95", "I-86"],
        "freight": ["consumer goods", "food and beverages", "dairy", "machinery", "apples"],
        "ports": ["Port of New York and New Jersey", "Peace Bridge (Buffalo)", "Champlain border crossing"],
        "neighbors": ["NJ", "PA", "CT", "MA", "VT"],
        "equipment": ["Dry Van", "Box Truck", "Reefer"],
        "note": "New York City is the country's largest consumer market, with congested deliveries and strong inbound demand. Upstate, the I-90 Thruway and Canadian border crossings near Buffalo and Champlain carry cross-border trade.",
    },
    "NC": {
        "hubs": ["Charlotte", "Greensboro", "Raleigh", "Wilmington", "Winston-Salem"],
        "interstates": ["I-40", "I-85", "I-95", "I-77", "I-26", "I-74"],
        "freight": ["furniture", "pork and poultry", "textiles", "pharmaceuticals", "lumber"],
        "ports": ["Port of Wilmington", "Port of Morehead City"],
        "neighbors": ["VA", "TN", "GA", "SC"],
        "equipment": ["Dry Van", "Reefer", "Flatbed"],
        "note": "North Carolina has a broad manufacturing base including furniture, textiles and pharmaceuticals, plus large hog and poultry operations in the east. Charlotte is a major distribution hub on I-85 and I-77.",
    },
    "ND": {
        "hubs": ["Fargo", "Bismarck", "Grand Forks", "Minot", "Williston"],
        "interstates": ["I-94", "I-29"],
        "freight": ["wheat and grain", "crude oil and frac sand", "oil field equipment", "sugar beets", "sunflowers"],
        "ports": ["Pembina border crossing", "Portal border crossing"],
        "neighbors": ["MN", "SD", "MT"],
        "equipment": ["Flatbed", "Hotshot", "Step Deck"],
        "note": "North Dakota's market is split between Red River Valley agriculture in the east and Bakken oil field activity in the west around Williston. Hotshot and flatbed work follow drilling activity.",
    },
    "OH": {
        "hubs": ["Columbus", "Cleveland", "Cincinnati", "Toledo", "Dayton"],
        "interstates": ["I-70", "I-71", "I-75", "I-77", "I-80", "I-90"],
        "freight": ["auto parts and vehicles", "steel", "consumer goods", "plastics and rubber", "machinery"],
        "ports": ["Rickenbacker inland port", "Port of Toledo", "Port of Cleveland"],
        "neighbors": ["PA", "WV", "KY", "IN", "MI"],
        "equipment": ["Dry Van", "Flatbed", "Step Deck"],
        "note": "Ohio is within a day's drive of much of the US population, making Columbus a major distribution center. Auto, steel and heavy manufacturing keep flatbed and dry van demand steady across the state.",
    },
    "OK": {
        "hubs": ["Oklahoma City", "Tulsa", "Lawton", "Enid"],
        "interstates": ["I-35", "I-40", "I-44"],
        "freight": ["oil and gas equipment", "cattle and beef", "wheat", "aerospace parts"],
        "ports": ["Tulsa Port of Catoosa"],
        "neighbors": ["KS", "MO", "AR", "TX", "NM", "CO"],
        "equipment": ["Flatbed", "Hotshot", "Dry Van"],
        "note": "Oklahoma's energy industry drives flatbed and hotshot demand, while I-35 and I-40 cross in Oklahoma City carrying national through freight. The Port of Catoosa links Tulsa to river barge traffic.",
    },
    "OR": {
        "hubs": ["Portland", "Salem", "Eugene", "Medford"],
        "interstates": ["I-5", "I-84", "I-205", "I-82"],
        "freight": ["lumber and wood products", "fresh produce", "nursery plants", "beverages", "electronics"],
        "ports": ["Port of Portland"],
        "neighbors": ["WA", "ID", "NV", "CA"],
        "equipment": ["Flatbed", "Reefer", "Dry Van"],
        "note": "Oregon is a leading producer of lumber and plywood, and the Willamette Valley ships nursery stock and produce. Portland anchors I-5 and I-84 traffic, with mountain passes affected by winter weather.",
    },
    "PA": {
        "hubs": ["Philadelphia", "Pittsburgh", "Harrisburg", "Allentown", "Scranton"],
        "interstates": ["I-76", "I-80", "I-81", "I-78", "I-95", "I-79"],
        "freight": ["consumer goods", "steel and metals", "food products", "natural gas equipment", "chemicals"],
        "ports": ["Port of Philadelphia"],
        "neighbors": ["NY", "NJ", "DE", "MD", "WV", "OH"],
        "equipment": ["Dry Van", "Flatbed", "Reefer"],
        "note": "Central Pennsylvania's I-81 and I-78 corridors host some of the largest warehouse clusters in the Northeast. Western Pennsylvania adds steel and natural gas freight around Pittsburgh.",
    },
    "RI": {
        "hubs": ["Providence", "Warwick", "Cranston", "Pawtucket"],
        "interstates": ["I-95", "I-195", "I-295"],
        "freight": ["imported vehicles", "jewelry and metals", "seafood", "consumer goods"],
        "ports": ["Port of Providence", "Port of Davisville"],
        "neighbors": ["CT", "MA"],
        "equipment": ["Dry Van", "Box Truck"],
        "note": "Rhode Island is a small, mostly short-haul market on the I-95 corridor. The Port of Davisville handles imported vehicles, and Providence's port moves bulk and break-bulk cargo.",
    },
    "SC": {
        "hubs": ["Charleston", "Greenville", "Columbia", "Spartanburg"],
        "interstates": ["I-26", "I-85", "I-95", "I-20", "I-77"],
        "freight": ["auto parts and vehicles", "tires", "imported containers", "aerospace parts", "textiles"],
        "ports": ["Port of Charleston", "Inland Port Greer"],
        "neighbors": ["NC", "GA"],
        "equipment": ["Dry Van", "Flatbed", "Power Only"],
        "note": "South Carolina's Upstate along I-85 is a major auto and tire manufacturing region, linked to the Port of Charleston by rail through Inland Port Greer. I-26 is the key port-to-Upstate truck corridor.",
    },
    "SD": {
        "hubs": ["Sioux Falls", "Rapid City", "Aberdeen", "Watertown"],
        "interstates": ["I-90", "I-29", "I-190"],
        "freight": ["corn and soybeans", "cattle", "ethanol", "meat products"],
        "ports": [],
        "neighbors": ["ND", "MN", "IA", "NE", "WY", "MT"],
        "equipment": ["Reefer", "Dry Van", "Flatbed"],
        "note": "South Dakota's freight is rooted in agriculture, with grain, ethanol and livestock in the east and ranching in the west. Sioux Falls is the main distribution hub where I-90 meets I-29.",
    },
    "TN": {
        "hubs": ["Memphis", "Nashville", "Knoxville", "Chattanooga"],
        "interstates": ["I-40", "I-24", "I-65", "I-75", "I-81", "I-55"],
        "freight": ["consumer goods", "auto parts and vehicles", "air cargo", "chemicals", "whiskey"],
        "ports": ["Memphis intermodal rail yards", "Memphis air cargo hub", "Port of Memphis"],
        "neighbors": ["KY", "VA", "NC", "GA", "AL", "MS", "AR", "MO"],
        "equipment": ["Dry Van", "Power Only", "Flatbed"],
        "note": "Memphis combines a major air cargo hub, several Class I rail yards and the Mississippi River, making it a leading distribution city. Middle and East Tennessee add auto manufacturing and Nashville-area warehousing.",
    },
    "TX": {
        "hubs": ["Dallas", "Houston", "San Antonio", "Laredo", "El Paso"],
        "interstates": ["I-10", "I-35", "I-20", "I-45", "I-30", "I-40"],
        "freight": ["oil and gas equipment", "petrochemicals", "cross-border Mexico freight", "fresh produce", "consumer goods"],
        "ports": ["Port of Houston", "Laredo border crossing", "Port of Corpus Christi", "El Paso border crossing", "Pharr border crossing"],
        "neighbors": ["NM", "OK", "AR", "LA"],
        "equipment": ["Dry Van", "Flatbed", "Reefer"],
        "note": "Texas leads the nation in cross-border trucking with Mexico, centered on Laredo and I-35. Houston's port and refineries drive energy and petrochemical freight, while Dallas-Fort Worth is a national distribution hub.",
    },
    "UT": {
        "hubs": ["Salt Lake City", "Ogden", "Provo", "St. George"],
        "interstates": ["I-15", "I-80", "I-70", "I-84"],
        "freight": ["retail and e-commerce goods", "minerals and metals", "food products", "building materials"],
        "ports": ["Salt Lake City intermodal terminals"],
        "neighbors": ["ID", "WY", "CO", "AZ", "NV"],
        "equipment": ["Dry Van", "Flatbed", "Reefer"],
        "note": "Salt Lake City sits where I-15 and I-80 meet, making it the main distribution point for the Intermountain West. Mining and growing e-commerce warehousing shape the state's freight mix.",
    },
    "VT": {
        "hubs": ["Burlington", "Rutland", "Barre", "Brattleboro"],
        "interstates": ["I-89", "I-91", "I-93"],
        "freight": ["dairy", "maple syrup", "lumber", "granite and stone"],
        "ports": ["Highgate Springs border crossing", "Derby Line border crossing"],
        "neighbors": ["NH", "MA", "NY"],
        "equipment": ["Dry Van", "Flatbed", "Reefer"],
        "note": "Vermont is a small, rural market built around dairy, maple products, timber and granite quarrying near Barre. Freight volumes are low and rural routes can be slow, especially in winter.",
    },
    "VA": {
        "hubs": ["Norfolk", "Richmond", "Roanoke", "Winchester", "Harrisonburg"],
        "interstates": ["I-95", "I-81", "I-64", "I-66", "I-77", "I-85"],
        "freight": ["imported containers", "poultry", "coal", "furniture", "consumer goods"],
        "ports": ["Port of Virginia (Norfolk)", "Virginia Inland Port (Front Royal)"],
        "neighbors": ["MD", "WV", "KY", "TN", "NC"],
        "equipment": ["Dry Van", "Reefer", "Flatbed"],
        "note": "The Port of Virginia in Hampton Roads is a major East Coast container gateway, and I-81 through the Shenandoah Valley is a heavy truck corridor. The valley also has large poultry operations.",
    },
    "WA": {
        "hubs": ["Seattle", "Tacoma", "Spokane", "Yakima", "Kent"],
        "interstates": ["I-5", "I-90", "I-82", "I-405", "I-182"],
        "freight": ["imported containers", "apples and fruit", "aerospace parts", "lumber", "seafood"],
        "ports": ["Port of Seattle", "Port of Tacoma", "Blaine border crossing"],
        "neighbors": ["OR", "ID"],
        "equipment": ["Dry Van", "Reefer", "Flatbed"],
        "note": "Washington's Seattle and Tacoma ports feed Kent Valley warehouses, while central Washington ships apples and fruit from Yakima and Wenatchee. Snoqualmie Pass on I-90 can close in winter.",
    },
    "WV": {
        "hubs": ["Charleston", "Huntington", "Morgantown", "Parkersburg", "Martinsburg"],
        "interstates": ["I-64", "I-77", "I-79", "I-81", "I-68", "I-70"],
        "freight": ["coal", "natural gas equipment", "chemicals", "timber", "steel"],
        "ports": ["Heartland Intermodal Gateway"],
        "neighbors": ["OH", "PA", "MD", "VA", "KY"],
        "equipment": ["Flatbed", "Step Deck", "Dry Van"],
        "note": "West Virginia's freight is shaped by coal, natural gas and chemical production along the Kanawha and Ohio rivers. Mountainous terrain makes routes slower, and the eastern panhandle serves I-81 distribution.",
    },
    "WI": {
        "hubs": ["Milwaukee", "Madison", "Green Bay", "Appleton", "Eau Claire"],
        "interstates": ["I-94", "I-90", "I-43", "I-39", "I-41"],
        "freight": ["dairy and cheese", "paper products", "machinery", "beer and beverages", "cranberries"],
        "ports": ["Port Milwaukee", "Port of Green Bay"],
        "neighbors": ["MI", "MN", "IA", "IL"],
        "equipment": ["Reefer", "Dry Van", "Flatbed"],
        "note": "Wisconsin's dairy and cheese industry drives strong reefer demand, while the Fox Valley is a major paper-producing region. Milwaukee adds heavy machinery and beverage freight near the Chicago market.",
    },
    "WY": {
        "hubs": ["Cheyenne", "Casper", "Gillette", "Rock Springs", "Laramie"],
        "interstates": ["I-80", "I-25", "I-90"],
        "freight": ["coal", "oil and gas equipment", "soda ash", "cattle", "hay"],
        "ports": [],
        "neighbors": ["MT", "SD", "NE", "CO", "UT", "ID"],
        "equipment": ["Flatbed", "Hotshot", "Step Deck"],
        "note": "Wyoming is a major coal and energy state, with the Powder River Basin around Gillette and trona mining near Green River. I-80 carries heavy through freight but is known for high winds and winter closures.",
    },
}
